version: '3.8'

services:

  # Contenedor con base de datos
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db-inventario

    environment:
      MYSQL_DATABASE: almacen_db_test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: DuocUc..2025
      MYSQL_PASSWORD: DuocUc..2025
    ports:
      - "3307:3306"
    networks:
      - app-network

  inventario-app:
    build: .
    container_name: inventario-app
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/almacen_db_test?useSSL=true&serverTimezone=UTC&hibernate.jdbc.batch_versioned_data=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: DuocUc..2025
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    networks:
      - app-network

networks:
  app-network:
    driver: bridge